# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/georg/Software/cfiles/eis/3.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/georg/Software/cfiles/eis/3.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/georg/Software/cfiles/eis/3.0/CMakeFiles /home/georg/Software/cfiles/eis/3.0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/georg/Software/cfiles/eis/3.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EIS

# Build rule for target.
EIS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EIS
.PHONY : EIS

# fast build rule for target.
EIS/fast:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/build
.PHONY : EIS/fast

lib/alloc_space.o: lib/alloc_space.c.o

.PHONY : lib/alloc_space.o

# target to build an object file
lib/alloc_space.c.o:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/lib/alloc_space.c.o
.PHONY : lib/alloc_space.c.o

lib/alloc_space.i: lib/alloc_space.c.i

.PHONY : lib/alloc_space.i

# target to preprocess a source file
lib/alloc_space.c.i:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/lib/alloc_space.c.i
.PHONY : lib/alloc_space.c.i

lib/alloc_space.s: lib/alloc_space.c.s

.PHONY : lib/alloc_space.s

# target to generate assembly for a file
lib/alloc_space.c.s:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/lib/alloc_space.c.s
.PHONY : lib/alloc_space.c.s

lib/complex.o: lib/complex.c.o

.PHONY : lib/complex.o

# target to build an object file
lib/complex.c.o:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/lib/complex.c.o
.PHONY : lib/complex.c.o

lib/complex.i: lib/complex.c.i

.PHONY : lib/complex.i

# target to preprocess a source file
lib/complex.c.i:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/lib/complex.c.i
.PHONY : lib/complex.c.i

lib/complex.s: lib/complex.c.s

.PHONY : lib/complex.s

# target to generate assembly for a file
lib/complex.c.s:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/lib/complex.c.s
.PHONY : lib/complex.c.s

src/damping.o: src/damping.c.o

.PHONY : src/damping.o

# target to build an object file
src/damping.c.o:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/damping.c.o
.PHONY : src/damping.c.o

src/damping.i: src/damping.c.i

.PHONY : src/damping.i

# target to preprocess a source file
src/damping.c.i:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/damping.c.i
.PHONY : src/damping.c.i

src/damping.s: src/damping.c.s

.PHONY : src/damping.s

# target to generate assembly for a file
src/damping.c.s:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/damping.c.s
.PHONY : src/damping.c.s

src/getdata.o: src/getdata.c.o

.PHONY : src/getdata.o

# target to build an object file
src/getdata.c.o:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/getdata.c.o
.PHONY : src/getdata.c.o

src/getdata.i: src/getdata.c.i

.PHONY : src/getdata.i

# target to preprocess a source file
src/getdata.c.i:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/getdata.c.i
.PHONY : src/getdata.c.i

src/getdata.s: src/getdata.c.s

.PHONY : src/getdata.s

# target to generate assembly for a file
src/getdata.c.s:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/getdata.c.s
.PHONY : src/getdata.c.s

src/lsm.o: src/lsm.c.o

.PHONY : src/lsm.o

# target to build an object file
src/lsm.c.o:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/lsm.c.o
.PHONY : src/lsm.c.o

src/lsm.i: src/lsm.c.i

.PHONY : src/lsm.i

# target to preprocess a source file
src/lsm.c.i:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/lsm.c.i
.PHONY : src/lsm.c.i

src/lsm.s: src/lsm.c.s

.PHONY : src/lsm.s

# target to generate assembly for a file
src/lsm.c.s:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/lsm.c.s
.PHONY : src/lsm.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/EIS.dir/build.make CMakeFiles/EIS.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... EIS"
	@echo "... lib/alloc_space.o"
	@echo "... lib/alloc_space.i"
	@echo "... lib/alloc_space.s"
	@echo "... lib/complex.o"
	@echo "... lib/complex.i"
	@echo "... lib/complex.s"
	@echo "... src/damping.o"
	@echo "... src/damping.i"
	@echo "... src/damping.s"
	@echo "... src/getdata.o"
	@echo "... src/getdata.i"
	@echo "... src/getdata.s"
	@echo "... src/lsm.o"
	@echo "... src/lsm.i"
	@echo "... src/lsm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

